### ISSUE TITLE
Loosen engines restriction, which currently requires Node >= 12.17.0

### ISSUE THREAD

**Issue by bcoe** [aduh95/viz.js#11]
A recent release of `@compodoc/ngd-transformer` pulls in `@aduh95/viz.js`, which drops support of Node 10.

This is breaking upstream builds of [google-auth-library](https://github.com/googleapis/google-auth-library-nodejs/pull/1075).

Are there any load-bearing Node 12 features being used, or could you consider loosening the engines constraint to include Node 10?

Refs: https://github.com/compodoc/ngd/issues/68

**Comment by aduh95** [comment]
> Are there any load-bearing Node 12 features being used

Well, there are ESM, package exports, and worker_threads which are not available by default on Node.js 10.x

Worth noting the library also exports a `@aduh95/viz.js/sync` script which doesn't use any of those features, and may even be compatible with Node.js v6.x+. `compodoc` is using that very script (https://github.com/compodoc/ngd/blob/60dbb2ac17e1d87f75b2378975607e578ae2a1fd/src/modules/transformer/dist/engines/dot/dot.js#L193), so that means the test failures on the `google-auth-library` PR are actually false positive.

I'm fine with loosening as I understand there are folks out there who need support for Node.js v10.x, but I'm not sure what's the best way to signal to users that parts of the API will break on older versions.

**Comment by bcoe** [comment]
> I'm fine with loosening as I understand there are folks out there who need support for Node.js v10.x, but I'm not sure what's the best way to signal to users that parts of the API will break on older versions.

Perhaps you could add Node 10 to your test matrix, but only run the sync tests? This would ensurer that they continue working until Node 10 is EOL (soonish). I think it's okay to then expect folks upstream to use the appropriate part of the API -- we're only talking about a few months I believe?

I ideally don't want to turn off `--engines-strict`, because as we move towards the Node 10 EOL catching dependencies that require Node 12 is very important.

**Comment by bcoe** [comment]
@aduh95 I worked around this upstream by moving our `--engine-strict` test to `npm i --production` only, so this is no longer a high priority for me.

**Comment by aduh95** [comment]
I've removed the engine restriction and publish a new version. My plan is to re-introduce it after Node.js v10 reaches end-of-life.
