### ISSUE TITLE
v3.5 crash on render.browser.js  @ "new URL [...]"

### ISSUE THREAD

**Issue by sebbloc** [aduh95/viz.js#20]
Because "new URL" need absolute path
=> idea could be
new URL("render.wasm", document.location)
but document is not available at this moment ... :(

PS.: other thing 
can you compile a version without  "-s ASSERTIONS=1"
because we can't change wasm name without recompile everything

**Comment by aduh95** [comment]
> Because "new URL" need absolute path

Ah that's unfortunate, I didn't stumble upon this during my testing on the browser, but I did on the Node.js test which I resolved by adding `-s USE_ES6_IMPORT_META=0` to the link flags. 
Could you give more context on this error you are seeing: Are you building viz.js yourself or are you using the files from the npm package? Are you using a bundler? Do you get the error in the browser console or from your build chain?

> => idea could be
> new URL("render.wasm", document.location)
> but document is not available at this moment ... :(

Given the fact that `globalThis.location === document.location`, is there any reason to use `document.location` instead of `location`?


> PS.: other thing
> can you compile a version without "-s ASSERTIONS=1"
> because we can't change wasm name without recompile everything

Hum, I don't think I use the `-s ASSERTIONS` flag anywhere in the build chain, you should be able to pick up the files from the npm package or the [Releases](https://github.com/aduh95/viz.js/releases) page and be good to go.

**Comment by sebbloc** [comment]
you right i can use location, but don't change the "magic word" error

i use version "dist" on web page (not node.js)

@render.browser.js
change 
[...]q=new URL("render.wasm",!1)[...]
to
[...]q=new URL("viz.wasm",location)[...]

then i have error message: (because i ve change .warm name, so the magic word too)
"Uncaught (in promise) RuntimeError: abort(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 68 32 3e @+0). Build with -s ASSERTIONS=1 for more info.

**Comment by aduh95** [comment]
> found 3c 68 32 3e

```js
String.fromCodePoint(0x3c , 0x68, 0x32, 0x3e) === '<h2>'
```

It looks like your web server is serving an HTML file instead of the `render.wasm`. If you check the `Network` tab of your browser DevTools, you should be able to inspect what it's actually serving (maybe a 404 HTML error page?).

BTW, if you want to specify a custom url for the wasm file, you can specify a `locateFile` function as a parameter in your worker file:

```js
import initWASM from '@aduh95/viz.js/worker'; // or 'viz.js/dist/render.browser.js'

initWASM({
  locateFile() {
    return '/path/to/render.wasm';
  },
});
```

**Comment by sebbloc** [comment]
You right, i'v 404 error because of wrong path, i've corrected and it rock !
