### ISSUE TITLE
Please remove `dist` from `.gitignore` and then re-publish to `npm`

### ISSUE THREAD

**Issue by StoneCypher** [aduh95/viz.js#23]
You have all your builds and type files pointed at dist, but dist is in .gitignore and isn't committed. This means you have to manually go into node_modules and build every installed instance.

This removes dist from gitgnore, which will allow your build residues into github, and thus into npm. I have not subsequently rebuilt; that will come in a follow-up PR.

Right now most people can't use this from the npm package because there are no build instructions, the build scripts are missing, and there's nothing built in the repo, so it looks like to use this library you can't actually use npm, and you have to build from scratch, meaning every CI/CD build needs to install docker, bison, emscripten, and so on

I can't install several of those tools because they conflict with other things I'm doing

I hope you'll consider adding the builds and type files to github, and then re-publishing to npm, so that people can use this library straight from npm

**Comment by aduh95** [comment]
Hello, files present on the GitHub repo don't have to be the same as the one in the npm package. If you look at the `package.json` file, you can see all relevant dist files are listed there: https://github.com/aduh95/viz.js/blob/b0a74f7a4d5c84e71fd94c98e31deff9d7162fcb/package.json#L31-L42
That instructs the package manager to integrate those files in the published version and to upload them to the npm registry. 

Here's the file structure I get if I install my package on a new local project:

```console
$ mkdir viz-test; (cd viz-test; npm i @aduh95/viz.js; cd node_modules/@aduh95/viz.js && tree)

added 1 package, and audited 2 packages in 437ms

found 0 vulnerabilities
.
|____LICENSE
|____CHANGELOG.md
|____dist
| |____render_sync.cjs
| |____render.browser.js
| |____types.d.ts
| |____render_sync.d.ts
| |____index.cjs
| |____index.mjs
| |____index.d.ts
| |____render_async.d.ts
| |____render_async.cjs
| |____render.node.mjs
| |____render.wasm
|____async
| |____index.js
| |____index.d.ts
|____wasm
|____README.md
|____package.json
|____sync
| |____index.js
| |____index.d.ts
|____worker
```

As you can see, all the dist files are there, and not the files necessary to build the project.

> I hope you'll consider adding the builds and type files to github, and then re-publishing to npm, so that people can use this library straight from npm

I'd rather not, because those files would clutter the git repo with no clear benefit, and if you have an issue with the npm package, changing the `.gitignore` file won't help that.

Maybe I can help with the issue you are seeing with the npm package? You haven't shared the error message or the reproduction steps, that would help me help you.

**Comment by StoneCypher** [comment]
Hm.  It appears it was either a bad install from `npm` or cache corruption on my machine.  There was nothing in that directory, and I thought a look at github supported that, but on a new clean install there is.  I apologize for the mistaken claim.  I'm not entirely sure what happened.  I might have just mis-read something locally.

&nbsp;

> Maybe I can help with the issue you are seeing with the npm package? You haven't shared the error message or the reproduction steps, that would help me help you.

I would really appreciate that.  I've now hit on something completely unrelated.

I think I'm going to close this and open a new issue, for sanitation's sake.  [That issue is here, instead](https://github.com/aduh95/viz.js/issues/25).  Thanks for putting up with me
