### ISSUE TITLE
Help needed with using workerURL option

### ISSUE THREAD

**Issue by christianvoigt** [aduh95/viz.js#8]
Hi, I am currently trying to migrate some old code to your fork. I was using Viz.js in the browser with the workerURL option. Previously the workerURL was pointing to `full.render.js`. I simply changed the url to point to `browser.render.js` (which I copied to the test server's base folder) and used the code from the README:

```js
let viz;
async dot2svg(dot, options) {
  if (viz === undefined) {
    viz = new Viz({workerURL: "/browser.render.js"});
  }
  return viz.renderString(dot, options);
}
...
// In some async render function:
const svgString = await dot2svg(dotCode, settings);
console.log(svgString);
```
But this is not working. I am seeing nothing in the console. I checked `/browser.render.js` in the browser and the file is available. Is the workerURL option still supposed to work like this?

**Comment by aduh95** [comment]
Thanks for this issue, hopefully it should be easily fixable. Do you want to have a look at the attached PR to see if that fixes it?

For reference, the issue comes from the fact the worker module was expecting a call the its `init` function – useful to provide custom Emscripten options. The fix is to initiate with empty object if the worker receives a message before the `init` function is called.

**Comment by christianvoigt** [comment]
thanks, I will test the PR and post an update here.

**Comment by christianvoigt** [comment]
It took a while to get the build process working again on my computer. After some problems with yarn, I figured out that I had to run `yarn set version latest` to get it working. I also changed the emscripten version in the Makefile to `1.39.12` to match my installation. I hope that does not break anything.

With the new build my example code now returns some messages in the console: 

```console
render.browser.js:10 wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
render.browser.js:10 falling back to ArrayBuffer instantiation
render.browser.js:10 failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 68 74 6d @+0
render.browser.js:10 Uncaught (in promise) RuntimeError: abort(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 68 74 6d @+0). Build with -s ASSERTIONS=1 for more info.
```

**Comment by aduh95** [comment]
For the `Incorrect response MIME type. Expected 'application/wasm'.` part, it seems the webserver you are using doesn't use the appropriate MIME type for WASM file. If you are using the `file://` protocol, this is also the case BTW.

Regarding the `expected magic word 00 61 73 6d, found 3c 68 74 6d @+0` part, `3c 68 74 6d` corresponds to the ASCII chars `<htm`. Again, that could be an issue with the configuration of your web server, serving an HTML document instead of the WASM file. In the Network tab of your browser DevTools, can you check what is actually loaded when trying to fetch `render.wasm`?

**Comment by christianvoigt** [comment]
That is strange. I am using the parcel development server to test this. The file is available under localhost:[port]. The content type is `application/javascript; charset=UTF-8`.

**Comment by christianvoigt** [comment]
I think I found my error: I only copied `render.browser.js` to the root folder. I now copied the whole `/dist` folder. Now the error message disappeared.

But renderString still does not return anything.

**Comment by aduh95** [comment]
> But renderString still does not return anything.

What do you mean by that? Does it return `undefined`?

**Comment by christianvoigt** [comment]
No, renderString *does* return a promise, but the promise never resolves or fails. This leads to the following behaviour:

```js
console.log("before renderString"); // gets called, shows up in inspector
const result = await viz.renderString(dotString, options);
console.log("after renderString"); //  is never called, shows not up in inspector
console.log(result);
```

That's what I meant, sorry for being too vague about it.

**Comment by aduh95** [comment]
If you create an `index.html` file in the dist folder containing:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
  </head>
  <body>
    <script type="module">
      import Viz from "./index.mjs";

      let viz;
      async function dot2svg(dot, options) {
        if (viz === undefined) {
          viz = new Viz({ workerURL: "/render.browser.js" });
        }
        return viz.renderString(dot, options);
      }

      dot2svg("digraph { 1 -> 2 }").then((svg) => {
        document.body.innerHTML = svg;
      }, console.error);
    </script>
  </body>
</html>
```

And then spawn a web server with `python3 -m http.server` or equivalent, and visit the web page, what do you see?

For me, using Chromium 80+, the SVG is inserted on the page after loading as expected.
Using Firefox and Safari, it fails because of a lack of support for module workers; to make it work on those browser, you would need to remove the ES module specific syntax in `browser.render.js` (the two `export` declarations at the end of the file).

**Comment by christianvoigt** [comment]
I am testing this on Windows 10/Chrome 84. To use `python3 -m http.server` I had to edit my Registry to add correct mime types for `.js`, `.mjs` and `.wasm` files. After that the page is loading without errors or warnings, but I still see a blank page. Maybe my build is broken. Could you upload yours so I can try it out?

**Comment by aduh95** [comment]
I've managed to fix the failing CI, you should be able to grab the build there. Tell me if you got more interesting results.

**Comment by christianvoigt** [comment]
That was it. With the CI's build it is working now. Don't know what went wrong during my build. I also deleted the two exports and tested it in Firefox. Thank you for your help!
